// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using X_Libra_Catering.Server.Data;

#nullable disable

namespace X_Libra_Catering.Server.Migrations
{
    [DbContext(typeof(BdXLibraCateringContext))]
    [Migration("20260729004201_AddAuditFields")]
    partial class AddAuditFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("X_Libra_Catering.Server.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DIRECCION");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_MODIFICACION");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("TELEFONO");

                    b.HasKey("Id")
                        .HasName("PK_CLIENTES");

                    b.ToTable("CLIENTES", (string)null);
                });

            modelBuilder.Entity("X_Libra_Catering.Server.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("CLIENTE_ID");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ESTADO");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_CREACION");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_EVENTO");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_MODIFICACION");

                    b.Property<string>("NombreEvento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NOMBRE_EVENTO");

                    b.Property<int>("NumInvitados")
                        .HasColumnType("int")
                        .HasColumnName("NUM_INVITADOS");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TIPO_EVENTO");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("UBICACION");

                    b.HasKey("Id")
                        .HasName("PK_EVENTOS");

                    b.HasIndex("ClienteId");

                    b.ToTable("EVENTOS", (string)null);
                });

            modelBuilder.Entity("X_Libra_Catering.Server.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CATEGORIA");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_MODIFICACION");

                    b.Property<string>("ImagenRuta")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("IMAGEN_RUTA");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOMBRE");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PRECIO");

                    b.Property<bool>("RequiereRefrigeracion")
                        .HasColumnType("bit")
                        .HasColumnName("REQUIERE_REFRIGERACION");

                    b.HasKey("Id")
                        .HasName("PK_MENUS");

                    b.ToTable("MENUS", (string)null);
                });

            modelBuilder.Entity("X_Libra_Catering.Server.Models.PedidoCabecera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ESTADO");

                    b.Property<int>("EventoId")
                        .HasColumnType("int")
                        .HasColumnName("EVENTO_ID");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_MODIFICACION");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_PEDIDO");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("TOTAL");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int")
                        .HasColumnName("VEHICULO_ID");

                    b.HasKey("Id")
                        .HasName("PK_PEDIDO_CABECERA");

                    b.HasIndex("EventoId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("PEDIDO_CABECERA", (string)null);
                });

            modelBuilder.Entity("X_Libra_Catering.Server.Models.PedidoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("CANTIDAD");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_MODIFICACION");

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("MENU_ID");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int")
                        .HasColumnName("PEDIDO_ID");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PRECIO_UNITARIO");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("SUBTOTAL");

                    b.HasKey("Id")
                        .HasName("PK_PEDIDO_DETALLE");

                    b.HasIndex("MenuId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PEDIDO_DETALLE", (string)null);
                });

            modelBuilder.Entity("X_Libra_Catering.Server.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CapacidadKg")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("CAPACIDAD_KG");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DIRECCION");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit")
                        .HasColumnName("DISPONIBLE");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_MODIFICACION");

                    b.Property<double?>("Latitud")
                        .HasColumnType("float")
                        .HasColumnName("LATITUD");

                    b.Property<double?>("Longitud")
                        .HasColumnType("float")
                        .HasColumnName("LONGITUD");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MARCA");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("PLACA");

                    b.Property<bool>("TieneRefrigeracion")
                        .HasColumnType("bit")
                        .HasColumnName("TIENE_REFRIGERACION");

                    b.HasKey("Id")
                        .HasName("PK_VEHICULOS");

                    b.HasIndex("Placa")
                        .IsUnique()
                        .HasDatabaseName("UQ_VEHICULOS_PLACA");

                    b.ToTable("VEHICULOS", (string)null);
                });

            modelBuilder.Entity("X_Libra_Catering.Server.Models.Evento", b =>
                {
                    b.HasOne("X_Libra_Catering.Server.Models.Cliente", "Cliente")
                        .WithMany("Eventos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EVENTOS_CLIENTES");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("X_Libra_Catering.Server.Models.PedidoCabecera", b =>
                {
                    b.HasOne("X_Libra_Catering.Server.Models.Evento", "Evento")
                        .WithMany("Pedidos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PEDIDO_CABECERA_EVENTOS");

                    b.HasOne("X_Libra_Catering.Server.Models.Vehiculo", "Vehiculo")
                        .WithMany("Pedidos")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PEDIDO_CABECERA_VEHICULOS");

                    b.Navigation("Evento");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("X_Libra_Catering.Server.Models.PedidoDetalle", b =>
                {
                    b.HasOne("X_Libra_Catering.Server.Models.Menu", "Menu")
                        .WithMany("PedidoDetalles")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PEDIDO_DETALLE_MENUS");

                    b.HasOne("X_Libra_Catering.Server.Models.PedidoCabecera", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PEDIDO_DETALLE_PEDIDO_CABECERA");

                    b.Navigation("Menu");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("X_Libra_Catering.Server.Models.Cliente", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("X_Libra_Catering.Server.Models.Evento", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("X_Libra_Catering.Server.Models.Menu", b =>
                {
                    b.Navigation("PedidoDetalles");
                });

            modelBuilder.Entity("X_Libra_Catering.Server.Models.PedidoCabecera", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("X_Libra_Catering.Server.Models.Vehiculo", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
